### ISSUE TITLE
Almost there

### ISSUE THREAD

**Issue by richgain** [RemovedMoney326/Hubble-Pi#1]
Hi Santiago
Thanks for sharing this great project! I'm following along all the instructions and I almost have everything working.
I have RasPiOS running on a Raspberry Pi model 3B and have installed all the necessary software including xrdp (my first time using this!).
I can run the AstroCam app and see the preview on the screen in the RDP window.
But when I click the capture button, nothing happens and there are no pictures in the Astrophotography/JPG folder.
I tried running the app from the command line with the same result but after I quit I saw this appear:
```
pi@raspberrypi:~/AstroCameraApp/PythonScripts $ python3 AstroCam.py 
Start
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "AstroCam.py", line 108, in camHandler
    camera.capture(stream, format='jpeg')
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1423, in capture
    'Timed out waiting for capture to end')
picamera.exc.PiCameraRuntimeError: Timed out waiting for capture to end

```
Does any of this help to explain why I can't take pictures yet?
Cheers,
Richard Gain
![image](https://user-images.githubusercontent.com/1440566/85947277-97433b80-b941-11ea-8e6c-9afb7195e813.png)

**Comment by RemovedMoney326** [comment]
Hi Richard :),

wow, it's nice to see someone has already tried replicating my project and
from the looks of it you are already practically done with the setup. I'm
happy my project instructions and python code are managing to be of use for
other members of the community!

Regarding the issue you have, it seems by looking at the last error output
"picamera.exc.PiCameraRuntimeError: Timed out waiting for capture to end"
that you may have run into a memory issue with the Picamera module
controlling the Pi. This means in essence that the GPU processing the
camera data is running out of allocated video memory and is unable to
capture images, thus timing out eventually. This is probably due to the HQ
camera modules higher resolution compared to the V1 and V2 camera modules,
which requires a higher memory capacity in order to not run out of it.

As for a possible solution; I stumbled upon this same issue too while
testing the camera initially using the command lines raspistill sequence
capture function. I managed to resolve it by increasing the amount of
allocated memory to the GPU from 128mb to 256mb, although admittedly that's
a ton and you probably won't need as much. Still I assume my AstroCam app
eats up a high amount of VRAM due to the live preview camera stream, so if
you have a GPU memory of, say for the Raspberry Pi 3, 64mb, try increasing
it to 128mb and if it still doesn't work to 256mb. You can do this from the
Raspberry Pi Software Configuration tools advanced settings section in the
Raspbian Settings menu.

I hope I was able to help and that this solution will provide useful for
you. If it works, I would also be thankful if you could let me know, so as
to include the VRAM requirement for the AstroCam script into the Hubble Pi
documentation. Should you have any further questions or if it still doesn't
work, do not hesitate to write back, as I would love to find out and work
on any possible bugs and issues within my code.

With kind regards and best of lucks, Santiago

**Comment by richgain** [comment]
Thanks for the speedy response.  I tried increasing the GPU allocation from 128mb to 256mb and rebooting but it didn't seem to make any difference. Would it help if I tried to run the app in debug mode to try and work out what is happening? I'm not a programmer but I do a lot of software beta testing at work and I don't mind digging into code a little bit.

Incidentally, when I run 'Camera Preview' the preview window displays correctly on the TFT screen but nothing shows up on the xrdp window. Is that the the expected behaviour?

Whilst I remember, I have some feedback for you on the instructions (which are generally superb, by the way). One section of the document that I got stuck on for a while was this paragraph in section 3.

> "The other two shortcuts can be set up by pasting the following two text files from the Github repository on the desktop and subsequently making them executable".

Eventually, I worked out that you have to paste them as text files and then change the file extension to ".desktop" which I had not known about before. That might be worth including for anyone else who is not familiar with creating shortcuts in this OS.

**Comment by RemovedMoney326** [comment]
Hello again Richard :),

firstlt, thank you for your feedback on the documentation! I will try to
keep it in mind once I make the next version of it with commentary on an
autoguide extension I'm already working on. I'm glad to hear that you found
it easy to follow and well written aside from that detail though :)

As for your issue, that's unfortunate to hear, I really thought VRAM would
be the cause of the issue, judging by the error code. Could you maybe open
the AstroCam.py file on the Thonny Python IDE built into Raspbian and
execute the program from there? Once opened, try taking a capture in
AstroCam and then send me the Python terminal output on the lower part of
the Thonny GUI. If something is wrong, an error should pop up there the
moment you click the capture button and it should probably give a more
detailed output on where exactly the program is failing to properly execute
the Picamera capture command.

Also, try doing a recording with the Record button too and see if the H264
video output works at least. To be honest I'm quite surprised in the case
that it's not a VRAM issue that the preview does work but the actual camera
functions don't, as most bugs I encountered during development had to do
with the camera module not initializing at times, leaving all functions
including the preview off. Maybe it's because of an issue with the output
path for the pictures, but that should show up in the Python console if
that's the case.

If you find out anything more, feel free to let me know, as I would very
much like to know the cause of this issue you have encountered, as well as
to figure out a way to solve it either by either modifying the python code
or the relevant raspbian setting and include it in the documentation.

With kind regards, Santiago

**Comment by RemovedMoney326** [comment]
PD: Oh yeah, I almost forgot; the Camera Preview window really is only
supposed to show up in the TFT screen. Unfortunately, this is due to the
way the Raspistill preview was implemented by the Raspberry Pi Foundation
in Raspbian, which makes the GPU output the preview directly as a video
signal instead of to the desktop (which is why you see the preview overlaid
on top of the desktop on the TFT screen instead of in a neat window or
something like that). I think there are ways to work around it, but I found
that it would be more convenient to build the preview into a window using a
camera stream like Eric did in the code I based AstroCam on, as the
raspistill preview also has other limitations such as not being able to
modify the camera settings once it's turned on. Still, it is more stable
and delivers a better quality preview, so I kept it for when one just wants
to find an object in the night sky befire taking pictures.

**Comment by richgain** [comment]
OK, thanks. Good advice to run it in Thonny. I ran it in debug mode and stepped through the program.
All good until I clicked the Capture button, then I got similar message to before:
```
Start
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/AstroCameraApp/PythonScripts/AstroCam.py", line 108, in camHandler
    camera.capture(stream, format='jpeg')
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1423, in capture
    'Timed out waiting for capture to end')
picamera.exc.PiCameraRuntimeError: Timed out waiting for capture to end
```
I wonder if it could have anything to do with installing Pillow whilst I was trying to get the scripts working.
Thanks for confirming that the Camera Preview doesn't display in the RDP window.
Best regards,
Richard

**Comment by richgain** [comment]
I just discovered that I don't have to click Capture. I get the same error after about 1 minute even if I just start the AstroCam program and leave it running.

**Comment by RemovedMoney326** [comment]
Hmmm, so it still is timing out, even with enough VRAM, that's strange. Also, it seems it has to do with the camera stream solution for the Tkinter preview window... I've tried to reproduce the error in my own Raspberry Pi 4, but as in the screenshot below, it runs flawlessly (the telescope is covered, so the camera isn't picturing anything, but it outputs the JPG and all correctly). As it seems to be something very specific to your setup, I would ask you to check the following list of questions/tests and write me back with the answers/results if you like, so I can narrow down the list of culprits.

1. Raspbian, Python and Picamera versions (try updating them to the latest ones if they aren't already)

2. Confirmation of the currently allocated VRAM to the GPU in the info window (I have 256mb, so ideally try allocating the same amount if you haven't already as per the previous advice)

3. HQ Camera Module test using Raspbian and Picamera; this is to test the camera hardware and whether or not it communicates to the Pi correctly. If you can, make a short Python capture script and test if it is able to capture an image upon running.

I will also try to check the program for performance issues with the camera stream for the preview window, as that seems to be at first glance the source of the problem. Since I still have a Raspberry Pi 2 from an older project lying around, I should also be able to test the AstroCam script using a weaker GPU and check whether older Raspberry Pi models are being taxed excessively by it in combination with the HQ Camera module. I will let you know in case I find out anything more or if I upload an updated version of the Python code.

![image](https://user-images.githubusercontent.com/64078691/86050173-afa37b00-ba53-11ea-85f8-17c501962ca7.png)

**Comment by richgain** [comment]
I agree, I think the stream is the problem. I commented out lines 107-112 and then found I could take a picture with the Capture button.

Raspbian = 2020-05-27-raspios-buster-armhf.img
Python = Python 3.7.3 (/usr/bin/python3)
Picamera = 1.13 (reinstalled it anyway, just in case)

VRAM = 256mb

As it was getting dark, I took three pictures:
1. using  raspistill -o image.jpg
2. using  "Picamera 3.1. Capturing to a file" script
3. using  raspistill -o image.jpg

1 and 3 look OK but 2 seems pretty dark


![image1-raspistill](https://user-images.githubusercontent.com/1440566/86055320-7bc85580-ba53-11ea-8068-16042b0cefa8.jpg)
![image2-picamera](https://user-images.githubusercontent.com/1440566/86055342-8387fa00-ba53-11ea-9f52-f313879328a8.jpg)
![image3-raspistill](https://user-images.githubusercontent.com/1440566/86055361-8aaf0800-ba53-11ea-9ff4-eda4d57531a3.jpg)

image1 = 4,596 KB
image2 = 163 KB
image3 = 4,307 KB

**Comment by RemovedMoney326** [comment]
Ok, the camera stream is the problem then, as it seems to be straining your Raspberry Pi 3 GPU, causing it to time out the capture event . I will try and test the AstroCam script later this day on my Raspberry Pi 2 to look for the same issue there. I will also start looking into ways to do the camera preview in a more performance-friendly fashion, so I will keep you informed once I update the AstroCam script on the repository here. 

If you want to try out something in the meantime, you can make a copy of the AstroCam.py file in your Raspberry Pi and play around with the lines for the camera preview to check if you can get it to work properly by modifying something. You can try changing the camera preview resolution to a lower one (the preview resolution is set each time the code has camera.resolution=(350,300) in it) or reducing the stream quality using the various PiCamera module setting for the camera.capture(strean) function (for more info on this, you can check the official PiCamera documentation from the Raspberry Pi foundation)

Lastly, I apologize for my code not correctly working after you went through all the trouble to replicate my project and all the inconveniences this might cause you. I hope I can still somehow fix it, although sadly I can't promise anything yet.

With kind regards, Santiago

**Comment by richgain** [comment]
Hi Santiago
Nothing to apologise for! You are sharing your experiments with the world. Everything gratefully received.
I am experimenting a bit more today and will let you know if I make progress.
Richard

**Comment by richgain** [comment]
OK, I've hacked your code about a bit and I have a working version now. The preview is a bit flickery but it works fine. There must be some issue with the stream function that I don't understand, so I'm not using it.

My version attached below the picture.

Regards,
Richard

![image](https://user-images.githubusercontent.com/1440566/86442292-7e51d600-bd05-11ea-9bbc-7898af5e4ce1.png)

[PreviewTest.zip](https://github.com/RemovedMoney326/Hubble-Pi/files/4868262/PreviewTest.zip)

**Comment by RemovedMoney326** [comment]
Hi Richard,
sounds great! I'm glad you managed to work it out then, seems like the issue really was the preview camera stream. If you want to, feel free to also send me the code you implemented to fix the issue (from what I understood, you did manage to implement the preview in a different way right?) so that I can review it and maybe pull it into the AstroCam.py file in the repository in its current or a modified way if it works better than my current stream implementation.
With regards, Santiago
Edit: Alternatively, you can also simply make a pull request for the lines you modified, whichever you prefer really. Thanks in advance and good work finding a solution for the issue!

**Comment by richgain** [comment]
Hi Santiago

Did you see the PreviewTest.zip file attached above? I'm not sure it's worth including in your AstroCam app as it simply uses camera.capture to repeatedly save a 480x300 jpeg preview file instead of a stream, but it works for me.
I adjusted the sizes of the windows to give me a bigger preview and a rectangular outline for the app.
I also changed a couple of default settings to the way I prefer them; binning to 2 and ISO to 400.

Cheers,
Richard

**Comment by richgain** [comment]
Aha! I have now managed to get your script to work on my RasPi 3B by changing just one line.
Line 108 is now:
camera.capture(stream, 'jpeg', use_video_port=True)

It still flickers but it's a much simpler fix.

**Comment by RemovedMoney326** [comment]
I see, you used the video port! That's actually quite a good idea, as the video port is better suited for doing sequential captures such as the one needed for a live preview stream. I guess that is why it runs now for you as well. Once I get the chance, I will implement and test out the stream using the video port on my own Hubble Pi and pull it into the AstroCam repository if it also works fine for me (even if my implementation works for me, if your line of code allows the program to run for the both of us, it still is worth implementing so that others don't step on the same issue.)

Good work in any case and you have my thanks for your patience and helpfulness, I hope you can enjoy your setup now that it's up and working :)

With kind regards, Santiago
