### ISSUE TITLE
Another GUI program

### ISSUE THREAD

**Issue by adambaskerville** [RemovedMoney326/Hubble-Pi#3]
Hello Santiago,

I did not realise someone else had also written a GUI program to interface with the Raspberry Pi HQ camera! I just uploaded a program I wrote which I have been using:

https://github.com/adambaskerville/AstroPitography

I saw in one of your issues that there was a flickering issue with the preview window. My program does not seem to have this so you are more than welcome to have a look and see if anything is of use with your project. 

Best regards,

Adam

**Comment by RemovedMoney326** [comment]
Hi Adam!

Just took a look at it and looks great, I would even say it's actually better than my program in most respects! Unfortunately, it doesn't seem there's all that much I can take away from it though, since your approach towards interfacing with the HQ camera module was completely different than mine; whereas you call and use a combination of opencv/raspistill to talk with the HQ camera in your Python script so to speak, I use the Picamera official Python package released by the Raspberry Pi foundation. This has the advantage of making the code easier to write in a way, but also removes some of my control over the way video previews can be handled at a graphics level, unlike your approach with OpenCV. 

Many thanks for drawing my attention on your project though as I will make sure to git clone it onto my computer just in case I do find something out I can implement from it in my code (if I do, I will make sure to credit you accordingly). Also, since your program is also for astrophotography from what I gathered, you might want to implement a grayscale option for taking pictures, as that way you can also use the HQ camera with filters for Nebulas and the like. Just a tip in case you want an easy to implement but substantially useful update for your capture software. But yeah, great work, really! :D

With kind regards, Santiago.R
